# Copyright (c) 2025 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from pathlib import Path
from subprocess import run
from textwrap import dedent


TEMPLATE = dedent("""\
    # Copyright (c) 2025 Nordic Semiconductor ASA
    # SPDX-License-Identifier: Apache-2.0

    # This file is generated from the IronSide versions.h header file.
    # Do not edit this file directly.

    {named_versions}

    config IRONSIDE_VERSION_TARGET
    \thex
    {conversion_defaults}
    \tdefault 0 # Invalid/unknown version

    config IRONSIDE_VERSION_TARGET_IS_SUPPORTED
    \tbool
    {platform_depends}

    config IRONSIDE_VERSION_TARGET_STRING
    \tstring
    """)

STR_TO_HEX_DEFAULT_TEMPLATE = (
    '\tdefault $({prefix}_hex) if IRONSIDE_VERSION_TARGET_STRING = "$({prefix}_str)"'
)

PLATFORM_DEPENDS_ON_TEMPLATE = (
    "\tdefault y if (IRONSIDE_VERSION_TARGET = $({prefix}_hex)) && {config_depends}"
)

MACRO_PATTERN = (
    r"(?P<ver>IRONSIDE_V[0-9]+_[0-9]+_[0-9]+_[0-9]+)"
    r"(_(?P<prop>[^\s]+))?"
    r"[\s]+"
    r"(?P<val>[^\s]+)"
)

MDK_DEFINE_TO_SOC = {
    "NRF54H20_XXAA": "SOC_NRF54H20",
    "NRF9230_ENGB_XXAA": "SOC_NRF9230_ENGB",
}


def main() -> None:
    parser = argparse.ArgumentParser(allow_abbrev=False)
    parser.add_argument(
        "--in-header",
        required=True,
        type=Path,
        help="Path to the ironside versions.h header file",
    )
    parser.add_argument(
        "--out-kconfig",
        type=argparse.FileType("w", encoding="utf-8"),
        default=sys.stdout,
        help="Path to write the generated Kconfig file to.",
    )
    args = parser.parse_args()

    proc = run(
        ["gcc", "-E", "-dM", str(args.in_header)],
        capture_output=True,
        text=True,
        check=True,
    )

    named_version_lines = []
    conversion_default_lines = set()
    platform_depend_lines = []

    platform_depends = defaultdict(set)

    for macro_m in re.finditer(MACRO_PATTERN, proc.stdout, flags=re.MULTILINE):
        version = macro_m["ver"]
        prefix = version.lower()
        value = macro_m["val"].strip().removeprefix('"').removesuffix('"').removesuffix("UL")
        match macro_m.group("prop"):
            case None:
                suffix = "hex"
            case "STRING":
                suffix = "str"
            case other:
                if other.startswith("SOC_") and int(value):
                    soc = other.removeprefix("SOC_")
                    platform_depends[prefix].add(MDK_DEFINE_TO_SOC[soc])
                continue

        name = f"{prefix}_{suffix}"
        named_version_lines.append(f"{name} := {value}")
        conversion_default_lines.add(STR_TO_HEX_DEFAULT_TEMPLATE.format(prefix=prefix))

    for prefix in platform_depends:
        soc_configs = sorted(platform_depends[prefix])
        if len(soc_configs) > 1:
            config_depends = f"({' || '.join(soc_configs)})"
        else:
            config_depends = soc_configs[0]
        platform_depend_lines.append(
            PLATFORM_DEPENDS_ON_TEMPLATE.format(prefix=prefix, config_depends=config_depends)
        )

    named_versions = "\n".join(sorted(named_version_lines))
    conversion_defaults = "\n".join(sorted(conversion_default_lines))
    platform_depends = "\n".join(sorted(platform_depend_lines))

    file_content = TEMPLATE.format(
        named_versions=named_versions,
        conversion_defaults=conversion_defaults,
        platform_depends=platform_depends,
    )

    args.out_kconfig.write(file_content)


if __name__ == "__main__":
    main()
